version: 2.1
orbs:
    snyk: snyk/snyk@2.3.0
jobs:
  build-and-test:
    working_directory: ~/juiceshop
    docker:
      - image: cimg/node:lts
    steps:
      - run:
          name: install-npm
          command: 'sudo npm install'
      - run:
          name: update-npm
          command: 'sudo npm install -g npm@latest'
      - run:
          name: install-snyk
          command: 'sudo npm install -g snyk'
      - run:
          name: snyk-help
          command: snyk --help
      - run:
          name: install-snyk-to-html
          command: 'sudo npm install snyk-to-html -g'
      - run:
          name: snyk auth
          command: snyk auth $SNYK_TOKEN
      - run:
          name: snyk test
          command: snyk test --severity-threshold=high --json-file-output=open-source-results.json || true
      - run:
           name: generate HTML report for open-source
           command: cat open-source-results.json | snyk-to-html -o open-source-results.html
      - store_artifacts:
           path: open-source-results.html
      - run:
           name: snyk monitor
           command: snyk monitor
      - run:
          name: snyk code test
          command: snyk code test --severity-threshold=high --json-file-output=code-results.json || true
      - run:
           name: generate HTML report for code
           command: cat code-results.json | snyk-to-html -o code-results.html
      - store_artifacts:
           path: code-results.html
workflows:
  snyk-build-and-test:
    jobs:
      - build-and-test